<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */

/* @var $this Mage_Checkout_Block_Onepage_Progress */
?>

<div id="opc-progress" class="block opc-block-progress">
	<div class="block-title">
    	<h2><?php echo $this->__('Progress') ?></h2>
	</div>
	
	<div class="block-content">
    	<dl class="opc-progress-list">
    		<?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
    		    <?php if ($this->isStepComplete('billing')): ?>
    				<dt class="complete">
    					<?php echo $this->__('Billing Address') ?>
    					<a href="#billing" class="button button-micro button-subtle" onclick="checkout.gotoSection('billing'); return false;"><?php echo $this->__('Edit') ?></a>
    				</dt>
    				<dd class="complete">
    					<address><?php echo $this->getBilling()->format('html') ?></address>
    				</dd>
    			<?php else: ?>
    				<dt class="incomplete">
    				    <?php echo $this->__('Billing Address') ?>
    				</dt>
    				<dd class="incomplete">
    				    <?php echo $this->__('Pending') ?>
    				</dd>
    			<?php endif; ?>
    		<?php endif; ?>
    	
    		<?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
    			<?php if ($this->isStepComplete('shipping')): ?>
    				<dt class="complete">
    					<?php echo $this->__('Shipping Address') ?>
    					<a href="#payment" class="button button-micro button-subtle" onclick="checkout.gotoSection('shipping');return false;"><?php echo $this->__('Edit') ?></a>
    				</dt>
    				<dd class="complete">
    					<address><?php echo $this->getShipping()->format('html') ?></address>
    				</dd>
    			<?php else: ?>
    				<dt class="incomplete">
    				    <?php echo $this->__('Shipping Address') ?>
    				</dt>
    				<dd class="incomplete">
    				    <?php echo $this->__('Pending') ?>
    				</dd>
    			<?php endif; ?>
    		<?php endif; ?>
    	
    		<?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
    			<?php if ($this->isStepComplete('shipping_method')): ?>
    				<dt class="complete">
    					<?php echo $this->__('Shipping Method') ?>
    					<a href="#shipping_method" class="button button-micro button-subtle" onclick="checkout.gotoSection('shipping_method'); return false;"><?php echo $this->__('Edit') ?></a>
    				</dt>
    				<dd class="complete">
    					<?php if ($this->getShippingMethod()): ?>
    						<?php echo $this->escapeHtml($this->getShippingDescription()) ?>
    		
    						<?php $_excl = $this->getShippingPriceExclTax(); ?>
    						<?php $_incl = $this->getShippingPriceInclTax(); ?>
    						
    						<?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
    							<?php echo $_incl; ?>
    						<?php else: ?>
    							<?php echo $_excl; ?>
    						<?php endif; ?>
    						
    						<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
    							(<?php echo $this->__('Incl. Tax') ?> <?php echo $_incl; ?>)
    						<?php endif; ?>
    					<?php else: ?>
    						<?php echo $this->__('Shipping method hasn\'t been selected yet.') ?>
    					<?php endif; ?>
    				</dd>
    			<?php else: ?>
    				<dt class="incomplete">
    				    <?php echo $this->__('Shipping Method') ?>
    				</dt>
    				<dd class="incomplete">
    				    <?php echo $this->__('Pending') ?>
    				</dd>
    			<?php endif; ?>
    		<?php endif; ?>
    	
    		<?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
    			<?php if ($this->isStepComplete('payment')): ?>
    				<dt class="complete">
    					<?php echo $this->__('Payment Method') ?>
    					<a href="#payment" class="button button-micro button-subtle" onclick="checkout.gotoSection('payment'); return false;"><?php echo $this->__('Edit') ?></a>
    				</dt>
    				<dd class="complete">
    					<?php echo $this->getPaymentHtml() ?>
    				</dd>
    			<?php else: ?>
    				<dt class="incomplete">
    				    <?php echo $this->__('Payment Method') ?>
    				</dt>
    				<dd class="incomplete">
    				    <?php echo $this->__('Pending') ?>
    				</dd>
    			<?php endif; ?>
    		<?php endif; ?>
    	</dl>
    </div>
</div>
