<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<p><?php echo $this->__('Return to') ?> <a href="<?php echo $this->getBackUrl() ?>"><?php echo $this->__('account') ?></a>.</p>
