<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<h1><?php echo $this->__('Account / Password') ?></h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="edit-account-info-form" class="scaffold-form">
	<?php echo $this->getBlockHtml('formkey')?>
	
	<div class="fieldset">
    	<h2 class="legend"><?php echo $this->__('Account Info') ?></h2>
    	
    	<ul class="form-list">
    		<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
    		
    		<li>
    			<label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
    			
    			<div class="input-box">
        			<input type="email" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" class="input-text required-entry validate-email" title="<?php echo $this->__('Email') ?>" />
        		</div>
    		</li>
    		
    		<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
    		<?php if ($_dob->isEnabled()): ?>
    			<li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
    		<?php endif ?>
    		
    		<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
    		<?php if ($_taxvat->isEnabled()): ?>
    			<li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
    		<?php endif ?>
    	
    		<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
    		<?php if ($_gender->isEnabled()): ?>
    			<li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
    		<?php endif ?>
    		
    		<li class="control">
    			<input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" <?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
    			<label for="change_password"><?php echo $this->__('Change password') ?></label>
    		</li>
    	</ul>
	</div>

	<div id="new-password-wrapper" class="fieldset" style="display:none;">
		<h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
		
		<ul class="form-list">
			<li>
				<label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
				
				<div class="input-box">
				    <input type="password" class="input-text" name="current_password" id="current_password" title="<?php echo $this->__('Current Password') ?>" />
				</div>
			</li>
			
			<li>
				<label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
				
				<div class="input-box">
				    <input type="password" class="input-text validate-password" name="password" id="password" title="<?php echo $this->__('New Password') ?>" />
				</div>
			</li>
			
			<li>
				<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
				
				<div class="input-box">
				    <input type="password" class="input-text validate-cpassword" name="confirmation" id="confirmation" title="<?php echo $this->__('Confirm New Password') ?>" />
				</div>
			</li>
		</ul>
	</div>
	
	<div class="buttons-set">
	    <button type="submit" class="button"><?php echo $this->__('Update') ?></button>
	</div>
</form>

<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('edit-account-info-form', true);
	function setPasswordForm(arg){
		if(arg){
			/*$('current_password').up(3).show();*/  /* original */
			$('new-password-wrapper').show();  /* GravDept, better selector. Doesn't rely on DOM parent traversal */
			
			$('current_password').addClassName('required-entry');
			$('password').addClassName('required-entry');
			$('confirmation').addClassName('required-entry');

		}else{
			/*$('current_password').up(3).hide();*/  /* Mage */
			$('new-password-wrapper').hide();  /* GravDept, better selector. Doesn't rely on DOM parent traversal */
			
			$('current_password').removeClassName('required-entry');
			$('password').removeClassName('required-entry');
			$('confirmation').removeClassName('required-entry');
		}
	}
	<?php if($this->getCustomer()->getChangePassword()): ?>
		setPasswordForm(true);
	<?php endif; ?>
//]]>
</script>
