<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>

<dl id="checkout-payment-method-load" class="billing-methods">
	<?php
	$methods = $this->getMethods();
	$oneMethod = count($methods) <= 1;
	?>
	
	<?php foreach ($methods as $_method): ?>
		<?php $_code = $_method->getCode(); ?>
		<dt>
			<?php if(!$oneMethod): ?>
				<input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
			<?php else: ?>
				<span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
				<?php $oneMethod = $_code; ?>
			<?php endif; ?>
			
			<label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
		</dt>
		
		<?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
			<dd><?php echo $html; ?></dd>
		<?php endif; ?>
	<?php endforeach; ?>
</dl>

<?php echo $this->getChildChildHtml('additional'); ?>

<script type="text/javascript">
//<![CDATA[
	<?php echo $this->getChildChildHtml('scripts'); ?>
	payment.init();
	<?php if (is_string($oneMethod)): ?>
	    payment.switchMethod('<?php echo $oneMethod ?>');
	<?php endif; ?>
//]]>
</script>
