<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>

<?php
/** @var $this Mage_Paypal_Block_Express_Review */
$billingBlock = $this->getChild('billing')->setFieldNamePrefix('billing')->setHideEmailAddress(true);
$shippingAddress = $this->getShippingAddress();
?>

<div class="grid-block">
	<h1><?php echo $this->__('Review Order') ?></h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    
    <script type="text/javascript">
    //<![CDATA[
        var countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>
    //]]>
    </script>
    
    <div class="paypal-review-order">
        <form method="post" id="order_review_form" class="stack-form" action="<?php echo $this->getPlaceOrderUrl() ?>">
        
            <?php if(!$billingBlock->isCustomerLoggedIn()): ?>
                <div class="block">
                    <div class="block-title">
                        <h2 class="legend"><?php echo $this->__('Customer Information') ?></h2>
                    </div>
                    
                    <div class="block-content lined">
                        <ul class="form-list form-list-narrow">
                            <li id="customer-info-form" class="address-form">
                                <div class="field">
                                    <label for="customer:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="customer-email" id="customer:email" value="<?php echo $this->escapeHtml($billingBlock->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            <?php endif ?>
            
            <div class="info-set grid">
                <div class="grid_6 alpha" id="billing-address">
                    <div class="block">
                        <div class="block-title">
                            <h2 class="legend"><?php echo $this->__('Billing Address') ?></h2>
                        </div>
                        
                        <div class="block-content lined">
                            <?php if ($shippingAddress): ?>
                                <?php echo $billingBlock->setShowAsShippingCheckbox(true)->toHtml(); ?>
                            <?php else: ?>
                                <?php echo $billingBlock->toHtml(); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                
            <?php if ($shippingAddress): ?>
                <div class="grid_6 omega" id="shipping-address">
                    <div class="block">
                        <div class="block-title">
                            <h2 class="legend"><?php echo $this->__('Shipping Address') ?></h2>
                        </div>
                        
                        <div class="block-content lined">
                            <?php echo $this->getChild('shipping')->setFieldNamePrefix('shipping')->setHideEmailAddress(true)->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="paypal-shipping-method block info-set">
                <div class="block-title">
                    <h2><?php echo $this->__('Shipping Method') ?></h2>
                </div>
                
                <div class="block-content lined">
                    <?php echo $this->getChild('shipping_method')->toHtml(); ?>
                </div>
            <?php endif; ?>
            </div>
        
            <div class="info-set block">
                <div class="block-title">
                    <h2 class="legend">
                        <?php echo $this->__('Items in Your Shopping Cart') ?>
                        <a class="button button-small button-subtle" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Cart') ?></a>
                    </h2>
                </div>
                
                <div class="block-content lined">
                    <div id="details-reload">
                        <?php echo $this->getChildHtml('details') ?>
                    </div>
                </div>
            </div>
            
            <?php echo $this->getChildHtml('agreements'); ?>
            
            <div class="buttons-set buttons-set-order" id="review-buttons-container">
                <button type="button" id="review_button" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
                <button type="button" id="review_submit" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
                <button type="button" id="update_order" class="button button-small button-subtle btn-checkout"><span><span><?php echo $this->__('Update Order Data') ?></span></span></button>
                
                <span class="please-wait" id="review-please-wait" style="display:none;"><?php echo $this->__('Sending your order...') ?></span>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
// submit buttons are not needed when submitting with ajax
$('review_submit').hide();
if ($('update_shipping_method_submit')) {
    $('update_shipping_method_submit').hide();
}

<?php if ($this->getUseAjax()):?>
    OrderReviewController.prototype._submitOrder = function() {
        if (this._canSubmitOrder) {
            if (this._pleaseWait) {
                this._pleaseWait.show();
            }
            new Ajax.Request(this.form.action, {
                parameters: {isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {
                    try{
                        response = eval('(' + transport.responseText + ')');
                    } catch (e) {
                        response = {};
                    }
                    if (response.redirect) {
                        setLocation(response.redirect);
                        return;
                    }
                    if (response.success) {
                        setLocation('<?php echo $this->getSuccessUrl()?>');
                        return;
                    } else {
                        var msg = response.error_messages;
                        if (typeof(msg)=='object') {
                            msg = msg.join("\n");
                        }
                        if (msg) {
                            $('review-please-wait').hide();
                            alert(msg);
                            return;
                        }
                    }
                    $('review-please-wait').hide();
                    alert('<?php echo $this->jsQuoteEscape($this->__('Unknown Error. Please try again later.')); ?>');
                    return;
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                    $('review-please-wait').hide();
                }
            });
        }
    }
<?php endif ?>
PayPalExpressAjax = new OrderReviewController($('order_review_form'), $('review_button'),
    'shipping_method', null, 'details-reload'
);
PayPalExpressAjax.addPleaseWait($('review-please-wait'));
PayPalExpressAjax.setShippingAddressContainer($('shipping-address'));
PayPalExpressAjax.setShippingMethodContainer('shipping-method-container');
PayPalExpressAjax.shippingMethodsUpdateUrl = '<?php echo $this->escapeHtml($this->getUpdateShippingMethodsUrl()) ?>';
PayPalExpressAjax.setUpdateButton($('update_order'),'<?php echo $this->escapeHtml($this->getUpdateOrderSubmitUrl()) ?>','details-reload');
if ($('billing:as_shipping')) {
    PayPalExpressAjax.setCopyElement($('billing:as_shipping'));
}
//]]>
</script>
