<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.3
 */
?>

<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
	<script type="text/javascript">
	//<![CDATA[
		var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
	//]]>
	</script>
<?php endif; ?>

<?php /* GravDept. Hide this. Moved to separate template: /catalog/product/view/availability.phtml */ ?>
<?php /*
<?php if ($_product->isAvailable()): ?>
	<p class="availability in-stock"><?php echo $this->helper('catalog')->__('In Stock') ?></p>
<?php else: ?>
	<p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Out Of Stock') ?></p>
<?php endif; ?>
*/ ?>

<div class="price-box-bundle">
	<?php echo $this->getPriceHtml($_product) ?>
</div>

<?php echo $this->getChildHtml('bundle_prices') ?>
